config/routes.rb
WebApp::Application.routes.draw do
  root to: 'static_pages#home'
  
  #get "static_pages/home"
  match 'home'       => 'static_pages#home'
  # match 'portfolio'  => 'static_pages#portfolio'
  # match 'services'   => 'static_pages#services'
  # match 'about'      => 'static_pages#about'
  # match 'blog'       => 'static_pages#blog'
  # #match 'contact'    => 'static_pages#contact'
  # #post 'contact'     => 'static_pages#contact'
  # match 'feed'       => 'static_pages#feed'

  resources :authors

  resources :author_sessions, only: [ :new, :create, :destroy ]

  match 'login'  => 'author_sessions#new'
  match 'logout' => 'author_sessions#destroy'
  
  resources :comments
  resources :articles
  

  resources :tags
  resources :projects
  resources :messages

  match 'contact'  => 'messages#new'   
  
  resources :archives, only: [ :index, :show ]

  match 'archives'  => 'archives#index'

  match '/archives' => 'static_pages#archives', :as  => :archives


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_filter  :set_archive_list

  def home

  end

  def portfolio
    
    @projects     = Project.limit(5).order("created_at DESC")
    @project      = Project.last
  end

  def services

  end

  def about

  end

  def blog
    
    @recent_posts = Article.limit(5).order("created_at DESC")
    @categories   = Tag.limit(6).order("name")
    @article      = Article.last

  end

   def set_archive_list
    
    posts = Article.find(:all,:order => "created_at DESC")
    @archive_list = posts.collect do |p|
      [p.created_at.strftime("%b %Y"), p.created_at.year, p.created_at.month]
    end
    @archive_list.uniq!
  end


  def contact
    binding.pry
    def new
    @message = Message.new
   end

  def create
    @message = Message.new(params[:message])
   
    if @message.valid?
       @email = "railspup@gmail.com"
        @from_email    = @message.email
        @from_name     = @message.name
        @from_message  = @message.content
        
      Pony.mail({
        :to      => @email,
        :from    => @message.email,
        :subject => "You have a new message from #{@from_name}",
        :body    => 

       
        

"You have received a messagefrom 5280 Web Design.



Name:    #{@message.name}
Email:   #{@message.email}
Message: #{@message.content}
       
        



      "
      })
      # TODO send message here
     
      redirect_to root_url, :flash => { :success => "Message sent! Thanks for contacting us" }

    else
      render "new"
    end
  end
    

  end

  def archives
    binding.pry
    start_time = Time.mktime( params[:year] || 2013, 
                              params[:month] || 1, 
                              params[:day] || 1)
    end_time = start_time.next_month
    @posts = Article.find(:all, 
      
      :conditions => ["created_at BETWEEN ? AND ?", start_time, end_time], 
      :order => "created_at DESC")
    render(:action => 'archives')
  end

end  # end of class

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_form.html.erb
<%= form_for @message do |f| %>
  <% if @message.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :content, "Message" %><br />
    <%= f.text_area :content, :rows => 5 %>
  </div>
  <div class="actions"><%= f.submit "Send Message" %></div>
<% end %>

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    

  </head>

  <body>
    <!-- MAIN CONTAINER BEGINS -->
  <div class="container">
    
  	<!-- /END Navigation -->
					
				
			<div class="row">
				<div class="span12">
    <!-- Welcome Text -->
					<h2>5280 Web Design is a small studio of web designers.</h2>
					<h2>We believe in effective and quality web design.</h2>
    <!-- /END Welcome Text -->
					<br>
					<br>
    <!-- "Who We Are" section -->

					<h2 class="section_header">Who We Are?</h2>				
	                <div class="taglinequite">
	                <p><b>5280 Web Design</b> is a small studio of web designers, developers, photographers and video experts. We all believe in effective design and are fully dedicated to creating websites that work for you and your customers. That's why we spend time getting to know you and your audience.</p>
	                <p>We feel it's the only way to create websites that effectively communicate your core messages and help you to engage with your users. We're all about quality. We are not IT people, we are humans with a real <b>desire to be of service</b>.</p>
	                </div>
                    <hr class="dashed">
    <!-- /END "Who We Are" section -->

					<br>
					<br>
    <!-- "Our Process" section -->
					<h2 class="section_header">Our Process</h2>				
					<ul class="thumbnails">
						<li class="span3">
						<img src="/assets/img/process1.png">
						<br>
						<br>
						<h4>Discover</h4>
						<p>The first stage of the process is to define the exact goals of the project or business. The discovery phase clearly states the problem and contains all of the information needed. Understanding the business properly will allow us to develop a unique solution for you</p>
						</li>
						<li class="span3">
						<img src="/assets/img/process2.png">
						<br>
						<br>
						<h4>Design</h4>
						<p>Now we begin to engage the creativity that is required to start developing focused design routes. Core choices about layout, type size and colour palettes are tested within a number of ideas to identify what works best in order to communicate your goals.</p>
						</li>
						<li class="span3">
						<img src="/assets/img/process3.png">
						<br>
						<br>
						<h4>Build</h4>
						<p>Once the design is signed off it is put into development. It is here where a working system that mimics the final design, is built with clean, semantic code that validates according to the W3C Organizations own community developed standards.</p>
						</li>
						<li class="span3">
						<img src="/assets/img/process4.png">
						<br>
						<br>
						<h4>Launch</h4>
						<p>Your system will require content. We will work with you to ensure you are unstoppable when it comes to using and populating your new website. Once launched, will be on hand to troubleshoot any queries you may have with regards to your site and its performance.</p>
						</li>
					</ul>
                    <hr class="dashed">
    <!-- /END "Our Process" section -->

    <!-- Studio Slider section -->
					<br>
					<br>
					<h2 class="section_header">Our Lovely Studio</h2>				
          			<div id="myCarousel" class="carousel slide">
           				<div class="carousel-inner">
              				<div class="item active">
                			<img src="/assets/img/studio1.jpg" alt="">
              				</div>
              				<div class="item">
                			<img src="/assets/img/studio2.jpg" alt="">
              				</div>
              				<div class="item">
                			<img src="/assets/img/studio3.jpg" alt="">
              				</div>
            			</div>
            			<a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
            			<a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
          			</div>
          			<br>
                    <hr class="dashed">
    <!-- /END Studio Slider section -->

    <!-- "The Team" section -->
          			<br>
					<h2 class="section_header">The Team</h2>				
					<ul class="thumbnails">
						<li class="span3">
						<img src="/assets/img/team1.png">
						<br>
						<br>
						<h4>Daniel</h4>
						<p><b>- Design Director.</b> Daniel combines an expert technical knowledge with a real eye for design. Working with clients from a wide range of industries, Daniel fully understands client objectives when working on a project, large or small.</p>
						</li>
						<li class="span3">
						<img src="/assets/img/team2.png">
						<br>
						<br>
						<h4>Rebecca</h4>
						<p><b>- Creative Director.</b> Being a creative director is a hard task, but Rebecca loves what she does. Her combination of knowledge and expertise is an important pillar in our agency & sometimes she brings us cookies!</p>
						</li>
						<li class="span3">
						<img src="/assets/img/team3.png">
						<br>
						<br>
						<h4>Marcel</h4>
						<p><b>- Client Services.</b> Marcel is an experienced marcoms practitioner and manages projects from inception to delivery. He understands the synergy between great design and commercial effectiveness which shines through on every project.</p>
						</li>
						<li class="span3">
						<img src="/assets/img/team4.png">
						<br>
						<br>
						<h4>Dave</h4>
						<p><b>- Design Master.</b>Dave began making websites when animated logos and scrolling text were cool, but has since found a love for simplicity, creating websites that are a pleasure to browse. Monkey Island Fan.</p>
						</li>
					</ul>
    <!-- /END "The Team" section -->
				
				</div><!-- /span12 -->
			</div><!-- /row -->
    </div> <!-- /container -->

	<!-- FOOTER -->
	

  </body>
</html>

app/views/static_pages/archives.html.erb
<div class="archives">
    <h2>Blog Archive</h2>

    <% @article_months.sort.reverse.each do |month, articles| %>
    <h3><%=h month.strftime("%B %Y") %></h3>
    <ul>
        <% for article in articles %>
        <li><%=h link_to article.title, article_path(article) %></li>
        <% end %>
    </ul>
    <% end %>
</div>

app/views/static_pages/blog.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    

  </head>

  <body>
    <!-- MAIN CONTAINER BEGINS -->
  <div class="container">
    
			<div class="row">
				<div class="span12">
    <!-- Welcome Text -->
					<h2>5280 Web Design Articles</h2>
    <!-- /END Welcome Text -->
    <!-- /Featured Image -->
				<br>
				<br>
				
							
				<img src="/assets/img/blog/post3.jpg" alt="">
    <!-- /END Feature Image -->

					<div class="thumbnails">
    				<!-- Begins Left Sidebar -->
						<div class="sidebar">
							<li class="span2">
								<p><h4>Recent Posts</h4></p>
								<ul>
        						<% for article in @recent_posts %>
        						<li><%=h link_to article.title, article_path(article) %></li>
       							 <% end %>
    							</ul>
    							<!-- /Start Select by month and year -->
	
    							<p><h4>Archives</h4></p>

    							
  								<ul>
								<% @archive_list.each do |item| -%>
								
    							

								<li><%= link_to(item[0], :action => 'archives', :year => item[1], :month => item[2]) %></li>
								<% end -%>
								</ul>
								
								
								

								<hr class="dashed">
								<p><h4>Video Widget</h4></p>
									<div class="video-container-post">
										<iframe src="http://player.vimeo.com/video/46304267?title=0&byline=0&color=C84D50" width="100%"  frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
					                </div>
								<hr class="dashed">

								<p><h4>Categories</h4></p>
								<ul>
        						<% for tag in @categories %>
        						<li><%=h link_to tag.name, tag_path(tag) %></li>
        							<% end %>
   								 </ul>
									
								<hr class="dashed">
						</li>
						</div><!-- /END Left Sidebar -->
    					
    					<!-- Begins Post -->
						<li class="span8">
						<br>
						<br>
						
							<p><h3 style="color:#b8413e"><%= @article.title %></h3></p>
							<p><b><%= @article.created_at.strftime("%b %d, %Y") %></b></p>
							<p style="font-size:10px; color:#b9413e"><i class="icon-folder-open";color:#b9413e></i> <%= tag_links(@article.tags) %> / <i class="icon-comment"></i> (<%= @article.comments.count %>) comments / <i class="icon-user"></i><%= @article.author_name %></p>

							<% if @article.image_file_name %>
  								<p><%= image_tag @article.image.url %></p>
							<% end %>

							
							<p><%= @article.body.gsub("\n", "<br>\n").html_safe%></p>

							<br></br>

							<span class='st_sharethis_large' displayText='ShareThis'></span>
							<span class='st_facebook_large' displayText='Facebook'></span>
							<span class='st_twitter_large' displayText='Tweet'></span>
							<span class='st_linkedin_large' displayText='LinkedIn'></span>
							<span class='st_tumblr_large' displayText='Tumblr'></span>
							<span class='st_reddit_large' displayText='Reddit'></span>
							<span class='st_pinterest_large' displayText='Pinterest'></span>
							<span class='st_email_large' displayText='Email'></span>
							
							
						</li>
    					<!-- /END Post -->
    					<!-- Begins Right Sidebar -->
						<div class="sidebar">
							<li class="span2">
								<h4>About The Author</h4>
									<p><img src="/assets/img/face60x60.png" alt="Marcel Newman"></p>
									<p><em>Daniel</em> is the lead designer at 5280 Web Design. He has been part of the crew for 8 years. Blogs about Ruby on Rails.</p>
								<hr class="dashed">
								<p><h4>Featured Project</h4></p>
									<img src="/assets/img/featured/f1.jpg">
								<hr class="dashed">
							</li>
						</div>
    					<!-- /END Right Sidebar -->

					</div><!-- /thumbnails div -->
				</div><!-- /span12 -->
			</div><!-- /row -->
    </div> <!-- /container -->

	<!-- FOOTER -->
	
 </body>
</html>

app/views/static_pages/blog2.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Agentrap - Responsive Bootstrap Agency Theme</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/stylesheets/bootstrap.css" rel="stylesheet">  
    <link href="/stylesheets/main.css" rel="stylesheet">

    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    
    <link href="/stylesheets/bootstrap-responsive.css" rel="stylesheet">
  <link rel='stylesheet' id='prettyphoto-css'  href="/stylesheets/prettyPhoto.css" type='text/css' media='all'>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png">
    
    <!-- Google Fonts call. Font Used Open Sans -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel='stylesheet' type='text/css'>

  </head>

  <body>
    <!-- MAIN CONTAINER BEGINS -->
  <div class="container">
    <div id="header_bg"></div> <!-- Display top header background -->
      <div class="row">
        <div class="span12">
          <div id="logo"><img src="/images/coollogo.png" alt="Logo"></div><!-- Display Logo -->
    
    <!-- Navigation -->
          <nav>
          <ul class="nav pull-right nav-pills">
            <li class="active">
                <a href="home.html">Home</a>
             </li>
            
                <li><a href="portfolio.html">Portfolio</a></li>
            <li><a href="services.html">Services</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="blog.html">Blog</a></li>
            <li><a href="contact.html">Contact</a></li>
          </ul>
          </nav>  
  	<!-- /END Navigation -->
					
				</div><!--/span12 -->
			</div> <!--/row -->
    <!-- /END TOP PART -->
		<br>
		<br>
		<br>
		<br>
		<br>
			<div class="row">
				<div class="span12">
    <!-- Welcome Message -->
					<h2>We write about web design, social media</h2>
					<h2>digital marketing and much more.</h2>
    <!-- /END Welcome Message -->
					<br>
					<br>
    <!-- Our Blog Section -->
					<h2 class="section_header">Our Blog</h2>
     				<div id="portfolio" class="row">
    				<!-- 1st Blog Post -->
						<div class="span4">
							<div class="view view-first">
								<img src="/assets/img/blog/post1-b.jpg" alt="Featured 1">
	                            <p><h4><a href="post-image-rs.html" style="color:#b8413e">Post with an image & right sidebar</a></h4></p>
	                            <p>This post comes with an image and a right sidebar.</p>
                            </div>
						</div>
    				<!-- 2nd Blog Post -->
						<div class="span4">
							<div class="view view-first">
								<img src="/assets/img/blog/post2-b.jpg" alt="Featured 1">
	                            <p><h4><a href="post-image-ls.html" style="color:#b8413e">Post with an image & left sidebar</a></h4></p>
	                            <p>This post comes with an image and a left sidebar.</p>
                            </div>
						</div>
    				<!-- 3rd Blog Post -->
						<div class="span4">
							<div class="view view-first">
								<img src="/assets/img/blog/post4-b.jpg" alt="Featured 1">
	                            <p><h4><a href="post-video-rs.html" style="color:#b8413e">Post with a video & right sidebar</a></h4></p>
	                            <p>This post comes with a video and a right sidebar.</p>
                            </div>
						</div>
    				<!-- 4th Blog Post -->
						<div class="span4">
							<div class="view view-first">
								<img src="/assets/img/blog/post5-b.jpg" alt="Featured 1">
	                            <p><h4><a href="post-video-ls.html" style="color:#b8413e">Post with a video & left sidebar</a></h4></p>
	                            <p>This post comes with a video and a left sidebar.</p>
                            </div>
						</div>
    				<!-- 5th Blog Post -->
						<div class="span4">
							<div class="view view-first">
								<img src="/assets/img/blog/post6-b.jpg" alt="Featured 1">
	                            <p><h4><a href="post-text-focus.html" style="color:#b8413e">Post with text focus</a></h4></p>
	                            <p>This post comes with a text focus design. No sidebar.</p>
                            </div>
						</div>
    				<!-- 6th Blog Post -->
						<div class="span4">
							<div class="view view-first">
								<img src="/assets/img/blog/post3-b.jpg" alt="Featured 1">
	                            <p><h4><a href="post-2sidebars.html" style="color:#b8413e">Post with an image & 2 sidebars</a></h4></p>
	                            <p>This post comes with an image and both, right and left sidebar.</p>
                            </div>
						</div>
					</div>				
                    <hr class="dashed">
    <!-- /END Our Blog Section -->
					<br>
					<br>
				</div><!-- /span12 -->
			</div><!-- /row -->
    </div> <!-- /container -->

	<!-- FOOTER -->
	<div id="end">
         <footer class="clearfix">
         	<div class="container">
         		<div class="row">
     <!-- About section -->
         			<ul class="span3">
         			<h5>ABOUT</h5>
        			<p>This is a beautiful theme and you know it. So, what are you waiting for? Buy it now, you'll no regret it.</p>
         			<img src="/assets/img/logo85x85.png" alt="Logo">
         			</ul>
     <!-- /END About section -->
     <!-- Socialize section -->
         			<ul class="span3">
 						<h5>SOCIALIZE</h5>
 						<p>We are social people. We love be in contact with everybody. We share beautiful things & thoughts.</p>
						<a href="#"><img src="/assets/img/social/Twitter.png" alt="Twitter"></a>
						<a href="#"><img src="/assets/img/social/Pinterest.png" alt="Pinterest"></a>
						<a href="#"><img src="/assets/img/social/Tumblr.png" alt="Tumblr"></a>
						<a href="#"><img src="/assets/img/social/Dribbble.png" alt="Dribbble"></a>
						<a href="#"><img src="/assets/img/social/Behance.png" alt="Behance"></a>
         			</ul>
     <!-- /END Socialize section -->
     <!-- Latest Tweet section -->
         			<ul class="span3">
 						<h5>LATEST TWEETS</h5>
 						<div id="jstwitter" class="clearfix">
						<ul id="twitter_update_list"></ul>
						</div>
						<script src="http://twitter.com/javascripts/blogger.js"></script><!-- Script Needed to load the Tweets -->
						<script src="http://api.twitter.com/1/statuses/user_timeline/envato.json?callback=twitterCallback2&count=3"></script>
     					<!-- To show your tweets replace "envato", in the line above, with your user. -->
         			</ul>
     <!-- /END Latest Tweets section -->
     <!-- Contact section -->
         			<ul class="span3">
         			<h5>CONTACT</h5>
         			<p><i class="icon-home icon-white"></i> Some Ave. 987</p>
         			<p><i class="icon-globe icon-white"></i> New York, USA</p>
         			<p><i class="icon-envelope icon-white"></i> your@email.com</p>
         			<p><i class="icon-thumbs-up icon-white"></i> Like to talk!</p>
         			</ul>
     <!-- /END Contact section -->


         		</div><!-- /row -->
         	</div><!-- /container -->
         </footer><!-- /footer -->
    </div><!-- /end -->

	    

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  	<script type='text/javascript' src="/assets/js/jquery.js"></script>
    <script type='text/javascript' src="/assets/js/bootstrap.js"></script>
  	<script type='text/javascript' src="/assets/js/jquery.prettyPhoto.js"></script>
    <script type='text/javascript' src="assets/js/agentrap.js"></script>

  </body>
</html>

app/views/static_pages/contact.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    

  </head>

  <body>
    <!-- MAIN CONTAINER BEGINS -->
  <div class="container">
    
			<div class="row">
				<div class="span12">
    <!-- Welcome Message -->
					<h2>Where in the world is 5280 Web Design?</h2>
					<h2>Beautiful, Denver Colorado</h2>
    <!-- /END Welcome Message -->
					<br>
					<br>
					<div class="contact_body">
					
					 <!--<img src="/assets/img/featured/citypark.jpg" alt=""> -->
					 <div style="text-align:center">

						    <p><img src="assets/img/featured/CityPark.jpg"></p></div>
					 
					</div>
    <!-- "Map" Message -->
					<h2 class="section_header hidden-phone">Map</h2>				
           			<div class="map hidden-phone"><iframe width="100%" height="420" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=4610+S+Ulster+St,+Denver,+CO&amp;aq=0&amp;oq=4610+S.+Ulster,+&amp;sll=39.630656,-104.895172&amp;sspn=0.309368,0.617294&amp;ie=UTF8&amp;hq=&amp;hnear=4610+S+Ulster+St,+Denver,+Colorado+80237&amp;t=m&amp;z=14&amp;iwloc=A&amp;ll=39.63183,-104.894889&amp;output=embed"></iframe></div>
    <!-- /END "Map" Message -->
    <!-- Contact Section -->
					<h2 class="section_header">Contact</h2>
					<div class="form-horizontal row">
						<ul class="span9">
							<form method="post" action="/contact",class="well">
							  <label style="font-size:18px;">Name:</label>
							  <input type="text" class="span6" name="contact_name" placeholder="Your Name...">
							  <br>
							  <br>
							  <label style="font-size:18px;">Email:</label>
							  <input type="text" class="span6" name="contact_email" placeholder="Your Email...">
							  <br>
							  <br>
							  <label style="font-size:18px;">Your Text:</label>
							  <textarea class="input-xlarge span6"name="contact_message" id="textarea" rows="12"></textarea>
							  <br>
							  <br>
							  <button type="submit" class="btn-danger btn btn-large">Submit</button>

							  
							</form>
							
						</ul>

						<ul class="span3">
							

						    <p><img src="assets/img/featured/4610ulster.jpg"></p>
					</div>
                    <hr class="dashed">
    <!-- /END Contact Section -->
					<br>
					<br>
				</div><!-- /span12 -->
			</div><!-- /row -->
    </div> <!-- /container -->

	<!-- FOOTER -->
	
  </body>
</html>

app/views/static_pages/portfolio.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
        
  </head>

  <body>
  	<!-- MAIN CONTAINER BEGINS -->
	<div class="container">
		
					
				
			<div class="row">
				<div class="span12">
    <!-- Welcome Text -->
					<h2>5280 Web Design-Projects</h2>
    <!-- /END Welcome Text -->
    <!-- /Featured Image -->
				<br>
				<br>
					<div style="text-align:center">
					<% if @project.image_file_name %>
  						<p><%= image_tag @project.image.url %></p>
					<% end %>
					</div>
							
			<!--	<img src="/assets/img/blog/post2.jpg" alt="Client Case"> -->
    <!-- /END Feature Image -->
    
    <!-- DESCRIPTION -->
					<div class="thumbnails">
    				<!-- Text -->
						<li class="span9">
						<br>
						<br>
						
							<h4><%= @project.title %></h4>

							
							<p><%= @project.body.gsub("\n", "<br>\n").html_safe%></p>

						</li>
    				<!-- sidebar -->
						<li class="span3">
							<p><h4>Launch Site</h4></p>
							
							<p><a href="http://<%= @project.website_name %>" style="color:#b8413e"><%= @project.website_name %></a></p>
							
							<br>
							<p><h4>Services</h4></p>
			         		<p><i class="icon-briefcase"></i> Web Design</p>
			         		<p><i class="icon-wrench"></i> Web Development</p>
			         		<p><i class="icon-comment"></i> Social Media</p>
							<br>
							<h4>Team Leader</h4>
							<p><img src="/assets/img/face60x60.png" alt="Marcel Newman"> Daniel S.</p>

						</li>



						<div class="sidebar">
							<li class="span2">
								<p><h4>Recent Work</h4></p>
								<ul>
        						<% for project in @projects %>
        						<li><%=h link_to project.title, project_path(project) %></li>
       							 <% end %>
    							</ul>
    						</li>	
    					</div>

    					
						
					</div>
    <!-- /END DESCRIPTION -->
					
				</div><!-- /span12 -->
			</div><!-- /row -->
    </div> <!-- /container -->

	<!-- FOOTER -->
	
  </body>
</html>

app/views/static_pages/rss.xml.erb
<rss version="2.0">
<channel>
<title>Daniel Stutzman</title>
<link>http://www.5280webdesign.com/</link>
<description>
A Boulder web developer shares tech reviews and how-tos
</description>
<language>en-us</language>