config/routes.rb
WebApp::Application.routes.draw do
  root to: 'static_pages#home'
  
  #get "static_pages/home"
  match 'home'       => 'static_pages#home'
  # match 'portfolio'  => 'static_pages#portfolio'
  # match 'services'   => 'static_pages#services'
  # match 'about'      => 'static_pages#about'
  # match 'blog'       => 'static_pages#blog'
  # #match 'contact'    => 'static_pages#contact'
  # #post 'contact'     => 'static_pages#contact'
  # match 'feed'       => 'static_pages#feed'

  resources :authors

  resources :author_sessions, only: [ :new, :create, :destroy ]

  match 'login'  => 'author_sessions#new'
  match 'logout' => 'author_sessions#destroy'
  
  resources :comments
  resources :articles
  

  resources :tags
  resources :projects
  resources :messages

  match 'contact'  => 'messages#new'   
  
  resources :archives, only: [ :index, :show ]

  match 'archives'  => 'archives#index'

  match '/archives' => 'static_pages#archives', :as  => :archives


end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :body, :tag_list, :image, :author_name

  has_many :comments
  has_many :taggings
  has_many :tags, :through => :taggings

  has_attached_file :image,
  :url  => "/assets/articles/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/articles/:id/:style/:basename.:extension"

  def self.search(search)
    if search
        find(:all, :conditions => ['title ILIKE ?', "%#{search}%"])
    else
       find(:all)
    end
  end 

  def tag_list
    return self.tags.join(", ")
  end # end of tag list

  def tag_list=(tags_string)
    self.taggings.destroy_all

    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq

    tag_names.each do |tag_name|
      tag = Tag.find_or_create_by_name(tag_name)
      tagging = self.taggings.new
      tagging.tag_id = tag.id
    end # end of do iteration
  end  # end of tag_list

  
end  # end of Article class




  

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, :except => [:index, :show]
  
  def index
    @articles = Article.paginate(:page => params[:page], :per_page => 12)
    
    @articles = Article.where("title ILIKE '%#{params[:search]}%'").order('id').page(params[:page]).per_page(12)
    
  end
  
  
  
  def show
    @article      = Article.find(params[:id])
    @recent_posts = Article.limit(5).order("created_at DESC")
    @categories   = Tag.limit(6).order("name")
  end

  def new
    @article = Article.new
  end

  def create
    
    @article = Article.new(params[:article])

    @article.save!

    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])

    @article.destroy

    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update_attributes(params[:article])

    flash[:message] = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def tag_links(tags)
    links = tags.collect{|tag| link_to tag.name, tag_path(tag)}
    return links.join(", ").html_safe
  end
end

app/views/articles/_comment.html.erb
<div class="comment">
  <h4>Comment by <%= comment.author_name %></h4>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
  
  <p><%= comment.body %></p>
</div>

app/views/articles/_comment_form.html.erb
<h3>Post a Comment</h3>

<%= form_for @article.comments.new do |f| %>
  <%= f.hidden_field :article_id %>
  <p>
    <%= f.label :author_name, "Your Name"  %>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article, :html => {:multipart => true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
   <p>
    <%= f.label :Category %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :author %><br />
    <%= f.text_field :author_name %>
  </p>
  <p>
    <% if @article.image_file_name %>
      <%= image_tag @article.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach a New Image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<h2>All Articles</h2>

<%= form_tag articles_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    
    <button type="submit" class="btn-danger btn btn-medium">Search</button>

                
                
                
  </p>
<% end %>



<% content_for :head, auto_discovery_link_tag(:atom, articles_url(format: "atom")) %>

<%= link_to image_tag("/assets/img/social/Feed.png"), "http://feeds.feedburner.com/5280webdesign" %>



<br></br>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>

<%= will_paginate %> 

<% if logged_in? %>
 <%= link_to "New Article", new_article_path, :class => "new_article" %>
<% end %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<div class="container">
    
			<div class="row">
				<div class="span12">
    <!-- Welcome Text -->
					<h2>5280 Web Design Articles</h2>
    <!-- /END Welcome Text -->
    <!-- /Featured Image -->
				<br>
				<br>
				
							
				<img src="/assets/img/blog/post3.jpg" alt="">
				
    <!-- /END Feature Image -->

					<div class="thumbnails">
    				<!-- Begins Left Sidebar -->
						<div class="sidebar">
							<li class="span2">
								<p><h4>Recent Posts</h4></p>
								<ul>
        						<% for article in @recent_posts %>
        						<li><%=h link_to article.title, article_path(article) %></li>
       							 <% end %>
    							</ul>	
								<hr class="dashed">
								<p><h4>Video Widget</h4></p>
									<div class="video-container-post">
										<iframe src="http://player.vimeo.com/video/46304267?title=0&byline=0&color=C84D50" width="100%"  frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
					                </div>
								<hr class="dashed">

								<p><h4>Categories</h4></p>
								<ul>
        						<% for tag in @categories %>
        						<li><%=h link_to tag.name, tag_path(tag) %></li>
        							<% end %>
   								 </ul>
									
								<hr class="dashed">
						</li>
						</div><!-- /END Left Sidebar -->
    					
    					<!-- Begins Post -->
						<li class="span8">
						<br>
						<br>
						
							<p><h3 style="color:#b8413e"><%= @article.title %></h3></p>
							<p><b><%= @article.created_at.strftime("%b %d, %Y") %></b></p>
							<p style="font-size:10px; color:#b9413e"><i class="icon-folder-open";color:#b9413e></i> <%= tag_links(@article.tags) %> / <i class="icon-comment"></i> (<%= @article.comments.count %>) comments / <i class="icon-user"></i><%= @article.author_name %></p>
							<div style="text-align:center">
							<% if @article.image_file_name %>
  								<p><%= image_tag @article.image.url %></p>
							<% end %>
							</div>

							
							<p><%= @article.body.gsub("\n", "<br>\n").html_safe%></p>

							<br></br>

							<span class='st_sharethis_large' displayText='ShareThis'></span>
							<span class='st_facebook_large' displayText='Facebook'></span>
							<span class='st_twitter_large' displayText='Tweet'></span>
							<span class='st_linkedin_large' displayText='LinkedIn'></span>
							<span class='st_tumblr_large' displayText='Tumblr'></span>
							<span class='st_reddit_large' displayText='Reddit'></span>
							<span class='st_pinterest_large' displayText='Pinterest'></span>
							<span class='st_email_large' displayText='Email'></span>
							

							



							<%= render :partial => 'comment', :collection => @article.comments %>

							<%= render :partial => 'comment_form' %>

							<%= link_to "<< Back to Articles List", articles_path %>

							<% if logged_in? %>
  							<%= link_to "edit", edit_article_path(@article) %>

  							<%= link_to "delete", article_path(@article), :method => :delete, :confirm => "Really delete the article?" %>
							<% end %>


							
						</li>
    					<!-- /END Post -->
    					<!-- Begins Right Sidebar -->
						<div class="sidebar">
							<li class="span2">
								<h4>About The Author</h4>
									<p><img src="/assets/img/face60x60.png" alt="Marcel Newman"></p>
									<p><em>Daniel</em> is the lead designer at 5280 Web Design. He has been part of the crew for 8 years. Blogs about Ruby on Rails.</p>
								<hr class="dashed">
								<p><h4>Featured Project</h4></p>
									<img src="/assets/img/featured/f1.jpg">
								<hr class="dashed">
							</li>
						</div>
    					<!-- /END Right Sidebar -->

					</div><!-- /thumbnails div -->
				</div><!-- /span12 -->
			</div><!-- /row -->
    </div> <!-- /container -->


