config/routes.rb
WebApp::Application.routes.draw do
  root to: 'static_pages#home'
  
  #get "static_pages/home"
  match 'home'       => 'static_pages#home'
  # match 'portfolio'  => 'static_pages#portfolio'
  # match 'services'   => 'static_pages#services'
  # match 'about'      => 'static_pages#about'
  # match 'blog'       => 'static_pages#blog'
  # #match 'contact'    => 'static_pages#contact'
  # #post 'contact'     => 'static_pages#contact'
  # match 'feed'       => 'static_pages#feed'

  resources :authors

  resources :author_sessions, only: [ :new, :create, :destroy ]

  match 'login'  => 'author_sessions#new'
  match 'logout' => 'author_sessions#destroy'
  
  resources :comments
  resources :articles
  

  resources :tags
  resources :projects
  resources :messages

  match 'contact'  => 'messages#new'   
  
  resources :archives, only: [ :index, :show ]

  match 'archives'  => 'archives#index'

  match '/archives' => 'static_pages#archives', :as  => :archives


end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :body, :developer_name, :website_name, :image, :author_name
  has_attached_file :image
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :require_login, :except => [:index, :show]
  
  def index
    @projects = Project.all
  end

  def show
    #binding.pry
    @project      = Project.find(params[:id])
    @projects     = Project.limit(5).order("created_at DESC")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])

    @project.save

    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:id])

    @project.destroy

    redirect_to projects_path
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update_attributes(params[:project])

    flash[:message] = "Portfolio project '#{@project.title}' Updated!"

    redirect_to project_path(@project)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project, :html => {:multipart => true}) do |f| %>
  <ul>
  <% @project.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :developer %><br />
    <%= f.text_field :author_name %>
  </p>

    
  <p>
    <%= f.label :website_name %><br />
    <%= f.text_field :website_name %>
  </p>
   
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <% if @project.image_file_name %>
      <%= image_tag @project.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach a New Image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit a Portfolio Project</h1>

<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<h1>All Portfolio Items</h1>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= link_to project.title, project_path(project) %>
    </li>
  <% end %>
</ul>
<% if logged_in? %>
<%= link_to "New Portfolio Project", new_project_path, :class => "new_project" %>
 <% end %>

app/views/projects/new.html.erb
<h1>Create a Portfolio Project</h1>

<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
        
  </head>

  <body>
  	<!-- MAIN CONTAINER BEGINS -->
	<div class="container">
		
					
				
			<div class="row">
				<div class="span12">
    <!-- Welcome Text -->
					<h2>5280 Web Design-Projects</h2>
    <!-- /END Welcome Text -->
    <!-- /Featured Image -->
				<br>
				<br>
					<div style="text-align:center">
					<% if @project.image_file_name %>
  						<p><%= image_tag @project.image.url %></p>
					<% end %>
					</div>
							
			<!--	<img src="/assets/img/blog/post2.jpg" alt="Client Case"> -->
    <!-- /END Feature Image -->
    
    <!-- DESCRIPTION -->
					<div class="thumbnails">
    				<!-- Text -->
						<li class="span9">
						<br>
						<br>
						
							<h4><%= @project.title %></h4>

							
							<p><%= @project.body.gsub("\n", "<br>\n").html_safe%></p>

						</li>
    				<!-- sidebar -->
						<li class="span3">
							<p><h4>Launch Site</h4></p>
							
							<p><a href="http://<%= @project.website_name %>" style="color:#b8413e"><%= @project.website_name %></a></p>
							
							<br>
							<p><h4>Services</h4></p>
			         		<p><i class="icon-briefcase"></i> Web Design</p>
			         		<p><i class="icon-wrench"></i> Web Development</p>
			         		<p><i class="icon-comment"></i> Social Media</p>
							<br>
							<h4>Team Leader</h4>
							<p><img src="/assets/img/face60x60.png" alt="Marcel Newman"> Daniel S.</p>

						</li>



						<div class="sidebar">
							<li class="span2">
								<p><h4>Recent Work</h4></p>
								<ul>
        						<% for project in @projects %>
        						<li><%=h link_to project.title, project_path(project) %></li>
       							 <% end %>
    							</ul>
    							<%= link_to "<< Back to Portfolio List", projects_path %>

								<% if logged_in? %>
  								<%= link_to "edit", edit_project_path(@project) %>

  								<%= link_to "delete", project_path(@project), :method => :delete, :confirm => "Really delete the portfolio item?" %>
								<% end %>
    						</li>	
    					</div>

    					
						
					</div>
    <!-- /END DESCRIPTION -->
					
				</div><!-- /span12 -->
			</div><!-- /row -->
    </div> <!-- /container -->

	<!-- FOOTER -->
	
  </body>
</html>
